### PR TITLE
:sparkles: impl FromStr for MacAddress

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Comment by rep-nop** [comment]
Hey! Thanks for the PR, looks good for the most part but I left some review changes. Once its all fixed up I'll go ahead and merge, then get 1.0 out on crates.io :)

**Comment by mmstick** [comment]
I'm not seeing any comments. What were they?

**Comment by rep-nop** [comment]
Ah sorry, my bad! Forgot to submit the review, oops.

**Comment by rep-nop** [comment]
I'll take a look tomorrow!

**Comment by rep-nop** [comment]
Looks good, thanks for the pull request! 1.0 will be out shortly :) :+1:

**Pull request merged**
